package com.github.devoxx.server.repository;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import com.github.devoxx.server.model.Actor;
import com.github.devoxx.server.model.Movie;
import com.github.javafaker.Faker;

/**
 * Created by david.wursteisen on 12/02/2015.
 */
public class MovieRepository {

    private final List<Movie> allMovies = Arrays.asList(
            new Movie("Contact"),
            new Movie("The Fountain"),
            new Movie("Resident Evil"),
            new Movie("The eye"),
            new Movie("Grindhouse -Planet Terror"),
            new Movie("9"),
            new Movie("War"),
            new Movie("AntiChrist"),
            new Movie("Watchmen"),
            new Movie("2012"),
            new Movie("Gamer"),
            new Movie("Quantum of Solace"),
            new Movie("The Deaths of Ian Stone"),
            new Movie("Jumper"),
            new Movie("Cloverfield"),
            new Movie("Hitman"),
            new Movie("Children of Men"),
            new Movie("Apocalypto"),
            new Movie("Smokin Aces"),
            new Movie("Rambo"),
            new Movie("Jumper"),
            new Movie("StarTrek"),
            new Movie("The Hills have eyes 2"),
            new Movie("Doomsday"),
            new Movie("Captivity"),
            new Movie("Doomsday"),
            new Movie("Surrogates"),
            new Movie("I am Legend"),
            new Movie("The Deaths of Ian Stone"),
            new Movie("Whiteout"),
            new Movie("The Fourth Kind"),
            new Movie("Transporter 2"),
            new Movie("Twilight 2"),
            new Movie("Gamer"),
            new Movie("Doomsday"),
            new Movie("Gamer"),
            new Movie("Machete"),
            new Movie("D.O.A"),
            new Movie("2012"),
            new Movie("Gamer"),
            new Movie("Crank imposed on DeathRace"),
            new Movie("Pathfinder"),
            new Movie("Antichrist"),
            new Movie("Grindhouse -Planet Terror"),
            new Movie("Deathrace"),
            new Movie("Horrorfest 2007"),
            new Movie("9"),
            new Movie("Resident Evil Extinction"),
            new Movie("300"),
            new Movie("2012"),
            new Movie("Crank 2 High Voltage"),
            new Movie("2012"),
            new Movie("Beowulf"),
            new Movie("Gamer"),
            new Movie("28 Weeks Later"),
            new Movie("Hellboy2"),
            new Movie("30 days of night"),
            new Movie("The Eye"),
            new Movie("300"),
            new Movie("Gamer"),
            new Movie("28 Weeks Later"),
            new Movie("Gamer"),
            new Movie("Smokin Aces"),
            new Movie("Gamer"),
            new Movie("War"),
            new Movie("Beowulf"),
            new Movie("Bourne Ultimatum"),
            new Movie("Deja Vu"),
            new Movie("D.O.A"),
            new Movie("Gamer"),
            new Movie("Grindhouse -Planet Terror"),
            new Movie("Sukiyaki Western Django"),
            new Movie("Nine"),
            new Movie("Sukiyaki Western Django"),
            new Movie("Surrogates"),
            new Movie("Nine"),
            new Movie("Burn After Reading"),
            new Movie("I am Legend"),
            new Movie("300"),
            new Movie("Grindhouse -Planet Terror"),
            new Movie("Cloverfield"),
            new Movie("Skinwalkers"),
            new Movie("The Unborn"),
            new Movie("Season of the Witch"),
            new Movie("The Unborn"),
            new Movie("Nine"),
            new Movie("Grindhouse"),
            new Movie("Nine"),
            new Movie("Daybreakers"),
            new Movie("Smokin Aces"),
            new Movie("Bourne Ultimatum"),
            new Movie("28 weeks later"),
            new Movie("Carriers"),
            new Movie("Deja Vu"),
            new Movie("Diary of the dead"),
            new Movie("Drag Me to Hell"),
            new Movie("Gamer"),
            new Movie("Captivity"),
            new Movie("Book of Eli"),
            new Movie("Indiana Jones and the Crystal Skull"),
            new Movie("Daybreakers"),
            new Movie("Grindhouse -Planet Terror"),
            new Movie("D.O.A"),
            new Movie("Alice in Wonderland"),
            new Movie("Captivity"),
            new Movie("One Missed Call"),
            new Movie("Nine"),
            new Movie("Skinwalkers"),
            new Movie("Star Trek"),
            new Movie("Nine"),
            new Movie("Pandorum"),
            new Movie("Nine"),
            new Movie("Terminator Salvation"),
            new Movie("Smokin Aces"),
            new Movie("Nine"),
            new Movie("NightWatch"),
            new Movie("Nine superimposed on Tokyo"),
            new Movie("District 9"),
            new Movie("9"),
            new Movie("Gi Joe"),
            new Movie("Nine"),
            new Movie("princecaspian"),
            new Movie("nine"),
            new Movie("war"),
            new Movie("nine"),
            new Movie("indiana jones crystal skull"),
            new Movie("nine"),
            new Movie("war"),
            new Movie("hellboy"),
            new Movie("nine"),
            new Movie("war"),
            new Movie("ninja assassins"),
            new Movie("timecrimes"),
            new Movie("nine"),
            new Movie("stardust"),
            new Movie("antichrist"),
            new Movie("9"),
            new Movie("2012"),
            new Movie("alice in wonderland"),
            new Movie("28 weeks later"),
            new Movie("boondock saints 2"),
            new Movie("nine"),
            new Movie("vacancy"),
            new Movie("a nightmare on elm street"),
            new Movie("vampires assistant"),
            new Movie("the unborn"),
            new Movie("die hard 4"),
            new Movie("the crazies"),
            new Movie("sukiyaki"),
            new Movie("the last airbender"),
            new Movie("war"),
            new Movie("Transporter 3"),
            new Movie("war"),
            new Movie("the unborn"),
            new Movie("watchmen"),
            new Movie("tokyo"),
            new Movie("transformers 2"),
            new Movie("next"),
            new Movie("nightwatch"),
            new Movie("tron 2"),
            new Movie("the collector"),
            new Movie("the fourth kind"),
            new Movie("the strangers"),
            new Movie("tropic thunder"),
            new Movie("thirst"),
            new Movie("whiteout"),
            new Movie("war"),
            new Movie("the promise"),
            new Movie("boondock saints 2"),
            new Movie("bourne ultimatim"),
            new Movie("taking of pelham 123"),
            new Movie("surrogates"),
            new Movie("bourne ultimatim"),
            new Movie("transformers 2"),
            new Movie("next"),
            new Movie("sweeny todd"),
            new Movie("no country for old men"),
            new Movie("tropic thunder"),
            new Movie("the fourth kind"),
            new Movie("transformers 2"),
            new Movie("Transporter 3"),
            new Movie("Star Trek"),
            new Movie("Nine"),
            new Movie("Captivity"),
            new Movie("Daybreakers"),
            new Movie("Dead Snow"),
            new Movie("Cloverfield"),
            new Movie("28 Weeks Later"),
            new Movie("Wolfman"),
            new Movie("9"),
            new Movie("Daybreakers"),
            new Movie("Deathrace"),
            new Movie("28 Weeks Later"),
            new Movie("Gamer"),
            new Movie("Doomsday"),
            new Movie("The Dark Knight"),
            new Movie("Gamer"),
            new Movie("9"),
            new Movie("Hellboy 2"),
            new Movie("Max Payne"),
            new Movie("Transformers"),
            new Movie("Valkrye"),
            new Movie("Skinwalkers"),
            new Movie("Shutter Island"),
            new Movie("Skinwalkers"),
            new Movie("Stardust"),
            new Movie("Skinwalkers"),
            new Movie("Drag Me To Hell"),
            new Movie("Wolfman"),
            new Movie("The Crazies"),
            new Movie("The Crazies / Skinwalkers Strobe"),
            new Movie("The Promise"),
            new Movie("Gi Joe"),
            new Movie("The Dark Knight"),
            new Movie("Apocalypto"),
            new Movie("PUlse"),
            new Movie("Children of Men"),
            new Movie("Batman Begins"),
            new Movie("Renaissance"),
            new Movie("Resident Evil Extinction"),
            new Movie("Nine"),
            new Movie("Push"),
            new Movie("Nighwatch"),
            new Movie("Nine"),
            new Movie("Deja Vu"),
            new Movie("Nightwatch"),
            new Movie("Nine"),
            new Movie("Punisher: Warzone"),
            new Movie("Hellboy 2 / Pan's Labyrinth Strobe"),
            new Movie("The Deaths Of Ian Stone"),
            new Movie("Shutter"),
            new Movie("Resident Evil: Extinction"),
            new Movie("Turistas"),
            new Movie("Gamer"),
            new Movie("Resident Evil: Extinction"),
            new Movie("2012"),
            new Movie("The Dark Knight"),
            new Movie("Push"),
            new Movie("Resident Evil: Extinction"),
            new Movie("Twilight: New Moon"),
            new Movie("Clash of the Titans"),
            new Movie("Nine"),
            new Movie("Deja Vu"),
            new Movie("Gamer"),
            new Movie("Clast of the Titans"),
            new Movie("Gamer"),
            new Movie("Twilight: New Moon"),
            new Movie("Ultraviolet"),
            new Movie("Clash of the Titans"),
            new Movie("Horrorfest Feature"),
            new Movie("Friday the 13th"),
            new Movie("300"),
            new Movie("Star Trek"),
            new Movie("Serenity"),
            new Movie("Pulse"),
            new Movie("Solomon Kane"),
            new Movie("Nine"),
            new Movie("Apocalypto"),
            new Movie("Batman Begins"),
            new Movie("Sherlock Holmes"),
            new Movie("Chronicles of Narnia: Prince Caspian"),
            new Movie("Prince of Persia"),
            new Movie("From Paris With Love"),
            new Movie("The Last Airbender"),
            new Movie("Watchmen"),
            new Movie("Postal"),
            new Movie("30 days of night"),
            new Movie("Halloween"),
            new Movie("The Unborn"),
            new Movie("Pans Labyrinth"),
            new Movie("300"),
            new Movie("Nine"),
            new Movie("Turistas"),
            new Movie("Final Destination"),
            new Movie("Horrorfest 2007"),
            new Movie("Pirates of the Carribean"),
            new Movie("Ultraviolet"),
            new Movie("Drag Me to Hell"),
            new Movie("Solomon Kane"),
            new Movie("Trick or Treat"),
            new Movie("V for Vendetta"),
            new Movie("Watchmen"),
            new Movie("Batman Begins"),
            new Movie("Cloverfield"),
            new Movie("Transformers 2"),
            new Movie("Saw 5"),
            new Movie("Quarantine"),
            new Movie("Saw"),
            new Movie("Season of the Witch"),
            new Movie("Ong bak 2"),
            new Movie("Max Payne"),
            new Movie("Killshot"),
            new Movie("The unborn"),
            new Movie("Nine"),
            new Movie("Max Payne"),
            new Movie("Ultraviolet"),
            new Movie("Tron"),
            new Movie("Bitch Slap"),
            new Movie("Norse"),
            new Movie("Percy Jackson..lightning thief"),
            new Movie("Paranormal Activity"),
            new Movie("The fourth kind"),
            new Movie("Doomsday"),
            new Movie("Book of Eli"),
            new Movie("Ultraviolet"),
            new Movie("Mutant Chronicles"),
            new Movie("Captivity"),
            new Movie("Season of the Witch"),
            new Movie("Ultraviolet"),
            new Movie("The Last Airbender"),
            new Movie("The Descent"),
            new Movie("Season of the Witch"),
            new Movie("Solomon Kane"),
            new Movie("Season of the Witch"),
            new Movie("Silent Hill"),
            new Movie("Season of the Witch"),
            new Movie("The Unborn"),
            new Movie("Turistas"),
            new Movie("The Unborn"),
            new Movie("Resident Evil Extinction"),
            new Movie("Texas Chainsaw Massacre: The Beginning"),
            new Movie("Skinwalkers"),
            new Movie("The Descent"),
            new Movie("Pulse"),
            new Movie("Resident Evil: Extinction"),
            new Movie("The Unborn"),
            new Movie("Resident Evil: Extinction"),
            new Movie("Prince of Persia"),
            new Movie("Clash of the Titans"),
            new Movie("The Descent"),
            new Movie("Max Payne"),
            new Movie("Solomon Kane"),
            new Movie("Stay Alive"),
            new Movie("Silent Hill"),
            new Movie("Stay Alive"),
            new Movie("Drag Me to Hell"),
            new Movie("Pulse"),
            new Movie("Clash of the Titans"),
            new Movie("Book of Eli"),
            new Movie("The Last Airbender"),
            new Movie("Dead Snow"),
            new Movie("The Unborn"),
            new Movie("The Deaths of Ian Stone"),
            new Movie("Tron 2"),
            new Movie("30 Days of Night"),
            new Movie("300"),
            new Movie("Alice In Wonderland"),
            new Movie("Tron 2"),
            new Movie("Amelia"),
            new Movie("A Nightmare on Elm Street"),
            new Movie("Tron 2"),
            new Movie("Avatar"),
            new Movie("Antichrist"),
            new Movie("Pulse"),
            new Movie("Tron 2"),
            new Movie("10,000 BC"),
            new Movie("Cloverfield"),
            new Movie("Tron 2"),
            new Movie("Bitchslap"),
            new Movie("Deja Vu"),
            new Movie("Watchmen"),
            new Movie("Whiteout"),
            new Movie("Seasons of the Witch"),
            new Movie("Quarantine"),
            new Movie("Wolfman"),
            new Movie("Rambo"),
            new Movie("Red Baron"),
            new Movie("Tron 2"),
            new Movie("Transporter 3"),
            new Movie("The Runaways"),
            new Movie("Season of the Witch"),
            new Movie("Whiteout"),
            new Movie("Twilight: Eclipse"),
            new Movie("Transformers 2"),
            new Movie("Bitchslap"),
            new Movie("Transformers 2"),
            new Movie("The Invisible"),
            new Movie("The Promise"),
            new Movie("Pirahana"),
            new Movie("Terminator Salvation"),
            new Movie("Avatar"),
            new Movie("Prince of Persia"),
            new Movie("Sukiyaki"),
            new Movie("Solomon Kane"),
            new Movie("Spiderman 3"),
            new Movie("Star Trek"),
            new Movie("Fast and the Furious"),
            new Movie("Star Trek"),
            new Movie("Final Destination"),
            new Movie("Amelia"),
            new Movie("Friday the 13th"),
            new Movie("Twilight: Eclipse"),
            new Movie("Final Destination"),
            new Movie("Turistas"),
            new Movie("District 13"),
            new Movie("Final Destination"),
            new Movie("Hellboy 2"),
            new Movie("GI Joe"),
            new Movie("Horrorfest 2010"),
            new Movie("Greenzone"),
            new Movie("Gamer"),
            new Movie("Horrorfest 2010"),
            new Movie("Alice in Wonderland"),
            new Movie("Gamer"),
            new Movie("30 Days of Night"),
            new Movie("300"),
            new Movie("An American Haunting"),
            new Movie("1408"),
            new Movie("An American Haunting"),
            new Movie("A Nightmare on Elm Street"),
            new Movie("Bermuda"),
            new Movie("An American Haunting"),
            new Movie("Gamer"),
            new Movie("Bermuda"),
            new Movie("Canyon"),
            new Movie("Ghost Rider"),
            new Movie("Chandni Goes to China"),
            new Movie("Chocolate"),
            new Movie("City Of Men"),
            new Movie("Deathrace"),
            new Movie("Bermuda"),
            new Movie("Deathrace"),
            new Movie("Gamer"),
            new Movie("Ghost Rider"),
            new Movie("D.O.A"),
            new Movie("Gamer"),
            new Movie("Avatar"),
            new Movie("Splice"),
            new Movie("Bourne Ultimatim"),
            new Movie("ClasH of the Titans"),
            new Movie("Gi joe"),
            new Movie("The Eye"),
            new Movie("Xmen: Wolverine"),
            new Movie("Watchmen"),
            new Movie("The Fountain"),
            new Movie("Tron 2"),
            new Movie("Iron Man 2"),
            new Movie("Shutter Island"),
            new Movie("Guardians of Gahoole"),
            new Movie("Wolfman"),
            new Movie("LOTR"),
            new Movie("The Fountain"),
            new Movie("Transformers 2"),
            new Movie("Inkheart"),
            new Movie("An American Haunting"),
            new Movie("City of Ember"),
            new Movie("King Kong"),
            new Movie("Xmen: Wolverine"),
            new Movie("Deja Vu"),
            new Movie("Fast And the Furious"),
            new Movie("The Eye"),
            new Movie("Knowing"),
            new Movie("City of Ember"),
            new Movie("Beastly"),
            new Movie("Inception"),
            new Movie("Beastly"),
            new Movie("Harry Potter"),
            new Movie("Expendables"),
            new Movie("Wanted"),
            new Movie("District 13"),
            new Movie("Transformers"),
            new Movie("The Fountain"),
            new Movie("Fast and the Furious"),
            new Movie("Oceans 13"),
            new Movie("Horrorfest 2007"),
            new Movie("Knowing"),
            new Movie("Skyline"),
            new Movie("Knowing"),
            new Movie("10,000 BC"),
            new Movie("The Dark Knight"),
            new Movie("Xmen: Wolverine"),
            new Movie("Pirates of the Carribean: At World's End"),
            new Movie("Stardust"),
            new Movie("Captivity"),
            new Movie("Next"),
            new Movie("The Dark Knight"),
            new Movie("Bourne Ultimatim"),
            new Movie("City of Men"),
            new Movie("300"),
            new Movie("The Girl with the Dragon Tattoo"),
            new Movie("Splice"),
            new Movie("Tron 2"),
            new Movie("Harry Potter: Half Blood Prince"),
            new Movie("Xmen: Wolverine"),
            new Movie("Clash Of the Titans"),
            new Movie("Chandni Goes to China"),
            new Movie("The Green Hornet"),
            new Movie("Xmen: Wolverine"),
            new Movie("Chandni Goes to China"),
            new Movie("Wolfman"),
            new Movie("Whiteout"),
            new Movie("Watchmen"),
            new Movie("V for vendetta"),
            new Movie("Watchmen"),
            new Movie("Scott Pilgrim"),
            new Movie("Ultraviolet"),
            new Movie("Avatar"),
            new Movie("Underworld: rise of the lycans"),
            new Movie("Turistas"),
            new Movie("Chandni Goes to China"),
            new Movie("Ultraviolet"),
            new Movie("Sourcerer's Apprentice"),
            new Movie("Transporter 2"),
            new Movie("The Matrix"),
            new Movie("The Last Airbender"),
            new Movie("Inception"),
            new Movie("The hurt locker"),
            new Movie("Terminator Salvation"),
            new Movie("Surrogates"),
            new Movie("Taking of Pelham 123"),
            new Movie("Super 8"),
            new Movie("Scott Pilgrim"),
            new Movie("Super 8"),
            new Movie("Contact"),
            new Movie("Kickass"),
            new Movie("Serenity"),
            new Movie("Avatar"),
            new Movie("10,000BC"),
            new Movie("Dark Streets"),
            new Movie("Bermuda"),
            new Movie("Drag Me To Hell"),
            new Movie("Horrorfest 2010"),
            new Movie("Devil"),
            new Movie("Dark Streets"),
            new Movie("Avatar"),
            new Movie("Stay Alive"),
            new Movie("Saw 5"),
            new Movie("Serenity"),
            new Movie("Saw 3D"),
            new Movie("Resident Evil: Afterlife"),
            new Movie("Smokin Aces"),
            new Movie("Sleep Dealer"),
            new Movie("Dark Streets"),
            new Movie("Spiderman 3"),
            new Movie("Sleep Dealer"),
            new Movie("DarkStreets"),
            new Movie("Sleep Dealer"),
            new Movie("Twilight Eclipse"),
            new Movie("Devil"),
            new Movie("Watchmen"),
            new Movie("Burlesque"),
            new Movie("Tron 2"),
            new Movie("Troy"),
            new Movie("Bitchslap"),
            new Movie("Chocolate"),
            new Movie("Batman Begins"),
            new Movie("30 Days of Night"),
            new Movie("300"),
            new Movie("Enter the Void"),
            new Movie("Centurion"),
            new Movie("Knowing"),
            new Movie("Horrorfest 2010"),
            new Movie("Resident Evil: Afterlife"),
            new Movie("Mutant Chronicles"),
            new Movie("Terminator Salvation"),
            new Movie("The Promise"),
            new Movie("Enter The Void"),
            new Movie("Wanted"),
            new Movie("Transformers 2"),
            new Movie("Tron 2"),
            new Movie("The Last Airbender"),
            new Movie("Law Abiding Citizen"),
            new Movie("Iron Man 2"),
            new Movie("Transporter 2"),
            new Movie("Transformers"),
            new Movie("Dark Streets"),
            new Movie("An American Haunting"),
            new Movie("A Nightmare on Elm Street"),
            new Movie("Clash of the Titans"),
            new Movie("A Nightmare on Elm Street"),
            new Movie("Clash of the Tiants"),
            new Movie("Centurion"),
            new Movie("Cloverfield"),
            new Movie("Scott Pilgrim"),
            new Movie("A Nightmare on Elm Street"),
            new Movie("Predators"),
            new Movie("Chain Letter"),
            new Movie("Predators"),
            new Movie("Iron Man 2"),
            new Movie("Clash of the Titans"),
            new Movie("Curse of the Golden Flower"),
            new Movie("Smokin Aces"),
            new Movie("A Nightmare on Elm Street"),
            new Movie("Percy Jackson"),
            new Movie("Centurion"),
            new Movie("Legend of the Guardians"),
            new Movie("Centurion"),
            new Movie("GI Joe"),
            new Movie("Underworld: Rise of the Lycans"),
            new Movie("Percy Jackson"),
            new Movie("Dont Be Afraid Of The Dark"),
            new Movie("Law Abiding Citizen"),
            new Movie("Legion"),
            new Movie("Clash of the Titans"),
            new Movie("Legion"),
            new Movie("Spiderman 2"),
            new Movie("Next"),
            new Movie("Burlesque"),
            new Movie("Iron Man 2"),
            new Movie("Ultraviolet"),
            new Movie("Iron Man 2"),
            new Movie("Watchmen"),
            new Movie("Ultraviolet"),
            new Movie("Sucker Punch"),
            new Movie("Tron 2"),
            new Movie("Burlesque"),
            new Movie("Tron 2"),
            new Movie("Iron Man 2"),
            new Movie("Sucker Punch"),
            new Movie("I spit on your grave"),
            new Movie("Spiderman 3"),
            new Movie("Dark Streets"),
            new Movie("Burlesque"),
            new Movie("Resident Evil: Afterlife"),
            new Movie("Xmen: Wolverine"),
            new Movie("Sucker Punch"),
            new Movie("Enter The Void"),
            new Movie("Sucker Punch"),
            new Movie("Dark Streets"),
            new Movie("Resident Evil"),
            new Movie("Dark Streets"),
            new Movie("Resident Evil"),
            new Movie("Gamer"),
            new Movie("Skinwalkers"),
            new Movie("Resident Evil: Afterlife"),
            new Movie("Scott Pilgrim"),
            new Movie("Iron Man 2"),
            new Movie("Burlesque"),
            new Movie("Incredible Hulk"),
            new Movie("28 Weeks Later"),
            new Movie("Iron Man 2"),
            new Movie("Gamer"),
            new Movie("28 Weeks Later"),
            new Movie("Iron Man 2"),
            new Movie("Resident Evil: Afterlife"),
            new Movie("Sucker Punch"),
            new Movie("Xmen: Wolverine"),
            new Movie("Tron 2"),
            new Movie("Sucker Punch"),
            new Movie("Pandorum"),
            new Movie("Rec 2"),
            new Movie("Sucker Punch"),
            new Movie("Tron 2"),
            new Movie("The Signal"),
            new Movie("Devil"),
            new Movie("Resident Evil: Afterlife"),
            new Movie("Step Up 3D"),
            new Movie("28 Weeks Later"),
            new Movie("10,000 BC"),
            new Movie("30 Days of Night"),
            new Movie("10,000 BC"),
            new Movie("30 Days of Night"),
            new Movie("300"),
            new Movie("9"),
            new Movie("Amelia"),
            new Movie("Alice In Wonderland"),
            new Movie("Step Up 3D"),
            new Movie("Kickass"),
            new Movie("An American Haunting"),
            new Movie("A Nightmare on Elm Street"),
            new Movie("Antichrist"),
            new Movie("Enter the Void"),
            new Movie("A Nightmare on Elm Street"),
            new Movie("Red Baron"),
            new Movie("Batman Begins"),
            new Movie("Ashes of Time"),
            new Movie("9"),
            new Movie("Burlesque"),
            new Movie("Ashes of Time"),
            new Movie("Battle for Terra"),
            new Movie("Beastly"),
            new Movie("Bermuda"),
            new Movie("Clash of the Titans"),
            new Movie("Book of Eli"),
            new Movie("Body of Lies"),
            new Movie("Book of Blood"),
            new Movie("Burlesque"),
            new Movie("Clash of The Titans"),
            new Movie("Bourne Ultimatim"),
            new Movie("Boondock Saints 2"),
            new Movie("The Runaways"),
            new Movie("Cash"),
            new Movie("Chain Letter"),
            new Movie("Cloverfield"),
            new Movie("Chandni goes to China"),
            new Movie("The Runaways"),
            new Movie("Scott Pilgrim"),
            new Movie("The Runaways"),
            new Movie("Scott Pilgrim"),
            new Movie("Gamer"),
            new Movie("Halloween"),
            new Movie("1408"),
            new Movie("Burlesque"),
            new Movie("The Deaths of Ian Stone"),
            new Movie("Sucker Punch"),
            new Movie("Final Destination"),
            new Movie("Super 8"),
            new Movie("Sleep Dealer"),
            new Movie("Super 8"),
            new Movie("Turistas"),
            new Movie("Shutter Island"),
            new Movie("Super 8"),
            new Movie("Surrogates"),
            new Movie("Super 8"),
            new Movie("Splice"),
            new Movie("Stay Alive"),
            new Movie("Surrogates"),
            new Movie("A Nightmare on Elm Street"),
            new Movie("An American Haunting"),
            new Movie("Skyline"),
            new Movie("Surrogates"),
            new Movie("Sleep Dealer"),
            new Movie("Surrogates"),
            new Movie("Sucker Punch"),
            new Movie("Silent Hill"));

    public List<Movie> movies() {

        return allMovies;

    }

    private final Faker faker = new Faker();

    // uggly cache
    private final Map<String, List<Actor>> cache = new HashMap<>();

    public List<Actor> actors(String id) {
        return cache.computeIfAbsent(id, (di) -> IntStream.range(1, 5)
                .boxed()
                .map((i) -> new Actor(faker.name().firstName(), faker.name().lastName()))
                .collect(Collectors.toList()));
    }
}
